### ISSUE TITLE
Outbound rules

### ISSUE THREAD

**Issue by ccrowhurstram** [Bikeman868/UrlRewrite.Net#13]
Just found your project and got my hopes up only to see outbound rules not supported yet!

How concrete are your plans for adding outbound rule support?

BTW,

This project looks really interesting as we've had no end of trouble with MS URL Rewrite, specifically:

* Using outbound rules to rewrite the content of SSRS report not really worked out (something to do with how JS in the ASP.Net UpdatePanel at a guess)
* Having to GAC install custom extensions

Thanks
Christian

**Comment by ccrowhurstram** [comment]
Scrap that question as I've just noticed the licence for this project is not compatible with proprietary software.

Thanks

**Comment by Bikeman868** [comment]
I didn't know about outbound rules when I originally wrote this library,
and I still don't know that much about them but I would like this to be a
drop-in replacement for the Microsoft one by being as close as possible to
100% backward compatible.

What was the problem with the licence, it wasn't my intention to stop
anyone from being able to use it, if you think the current licence does
then I will look at other licences I can adopt.

**Comment by ccrowhurstram** [comment]
Hi Martin, thanks for replying.

The licence issue... 

AFAIK, for our project to use the tool in our application, our application must also be licensed using [GNU General Public License v3](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)). This is due to the licence being ["strong copy-left"](https://en.wikipedia.org/wiki/Copyleft#Strong_and_weak_copyleft).

If your intent is to make this library open source without imposing restrictions on projects that use it, then a better choice would be [MIT license](https://tldrlegal.com/license/mit-license) (at least that is very common choice).

## Restricting derivative  work

If on the other hand you want impose some restrictions on derivative work (ie someone who forks your repo), then [LGPLv3](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)) looks like a good choice. 

In this way:
* a commercial project (say) that wants to use your library in their *application*, is free to do so without having to open source the project.
* someone who wants to fork your repo, makes changes to it, renames it (say), etc. That someone must also licence the work under the same (or compatible?) LGPLv3 license.

**Comment by ccrowhurstram** [comment]
Did you intend to change the license given the above?

I just did a quick google search, I it seems there is nothing legal wise to stop you. Here's a [stackexchange post](https://softwareengineering.stackexchange.com/questions/285150/changing-license-of-personal-github-repository) that seems to be a good reference

**Comment by Bikeman868** [comment]
I will go ahead and change the licence to the MIT one. Go ahead and build
my library into your tool.

When you start a repo GitHub asks you to choose a licence and I chose one
without taking much time to study the options. It looks like the MIT one
you suggest is a better fit for my original intent.

**Comment by Bikeman868** [comment]
After reviewing the various commonly used licences I decided that the Apache 2.0 licence best describes my intent for the software and have updated the files accordingly.

Thanks for pointing out this issue.

**Comment by ccrowhurstram** [comment]
Cool. That licence is also very permissive.

So this leaves

> How concrete are your plans for adding outbound rule support?

:-)

**Comment by Bikeman868** [comment]
Ahh, so little time and so much to do.

I definitely think it should be included and I want to do it. Right now I am focussed on adding granular permissions and an audit trail to Urchin so I am going to finish that first. After that I can take a look at how much functionality is provided for outbound rules in the Microsoft implementation and if this can be added with a couple of weeks effort it could be next.

Do you have any interest in being a contributor to the project?

**Comment by ccrowhurstram** [comment]
> Ahh, so little time and so much to do.

I know that feeling!

There is certainly motivation to become a contributor. The main interest would be to see a long outstanding issue with the Url Rewrite module fixed.

However, the reality is any contributions I can make would be minimal. This is because I see the following playing out...

### Outbound rules likely to be very time consuming to implement

I have an outstanding MSDN subscription case open with MS to fix the problem of rewriting SSRS report urls. 

They have been working on getting a fix on and off for the last 2 years! This suggest that outbound rules are hard to implement. Therefore, the task at hand might be extensive and a time sink.

There is a significant risk that if I did get sponsorship to help out, there might never be a delivery at the end of it.

### Risk of obsolescence due to ASP.Net Core

ASP.Net Core is a game changer. The official Url Rewrite might become legacy. Your library will likely suffer the same fate.

Just recently, Kestrel (ASP.Net core lightweight web server) has received some updates. These updates make it possible to serve requests without standing up IIS in front acting as a reverse proxy.

In a year from now, it's highly likely the project at work here will be migrating to Core. At which point, I would be looking for entirely different solution as IIS might not even be included in the stack.

---

PS. Sorry to put a negative slant on things!

**Comment by Bikeman868** [comment]
If outbound rules are hard and take a long time to implement, and will be obsolete soon then there seems to be little point in starting this project.

**Comment by ccrowhurstram** [comment]
Just to clarify, it's not the outbound rules that run the risk of obsolescence, it's the *entire* Url Rewrite module that run's this risk.

Url Rewrite module is native to IIS, and there are question marks over how long IIS will be relevant in a ASP.Net Core environment.

On the other hand, if IIS is still going to be commonly used as a reverse proxy in front of an ASP.Net core site / api, then URL Rewrite is still going to be relevant. In that case, it is worth investing further in development of your library as a "drop in" replacement.

**Comment by Bikeman868** [comment]
For anyone following this thread you might be interested to know that I have built an open-source load-balancer called "Gravity". One of the available processing nodes that can be configured implements these rewriting rules - I copied the code directly over so it's fully compatible.
Check out my "Gravity" repo.
This load-balancer is built on OWIN and hence more future proof.
