### ISSUE TITLE
Missing UrlRewrite.Utilities.RewriteNinjectModule class

### ISSUE THREAD

**Issue by michaelelleby** [Bikeman868/UrlRewrite.Net#14]
The documentation refers to a `RewriteNinjectModule` class, for using Ninject as IOC. However this class is nowhere in the source code?

**Comment by Bikeman868** [comment]
It looks like this class was removed when the Ioc.Modules package was integrated. This means that right now you have to use Ioc.Modules in your application if you want to replace any interface implementations with your application supplied ones.

Although Ioc.Modules is very lightweight, flexible and useful, I don’t want to force you to use it so something has to be changed. Your proposal of exposing all the concrete types is definitely one option and I will consider merging your pull request.

**Comment by Bikeman868** [comment]
I merged your pull request and corrected the documentation.

Although the classes are now public, I recommend you take a look at Ioc.Modules as a better way of defining IoC configuration requirements independently of the IoC container.

**Comment by michaelelleby** [comment]
I tried using the `IoC.Modules` component, but then the [NinjectFactory](https://github.com/Bikeman868/UrlRewrite.Net/blob/master/Solution/UrlRewrite-Net40/Utilities/NinjectFactory.cs) class would create a new Ninject `StandardKernel` thus ignoring my existing bindings, and since it does not expose this new kernel, it is not possible to register my own interfaces with it. This is a problem since I want to use custom actions and operations, which require repositories for lookup and those repositories should be provideded by Ninject.

**Comment by Bikeman868** [comment]
You can register your application classes with IoC by adding one or more `Package` classes as per the docs for `Ioc.Modules`.

If you need access to the Ninjet kernel for any other reason then you can copy the `NinjectFactory` class into your application, modify it any way you want then pass an instance of it to Url Rewrite when you initialize it.

**Comment by Bikeman868** [comment]
I have updated the documentation to provide a lot more information and sample code for the different IoC integration scenarios. Please review the changes and see if you still need the changes from your pull request. If you no longer feel that you need these classes to be public I would rather revert this check in and keep the size of the public footprint as small as possible. Thanks.

**Comment by michaelelleby** [comment]
Trying to create my own `IFactory` implementation called `IoCFactory`, Ninject throws an exception, saying now there are two registered classes for `IFactory`:
```
Ninject.ActivationException: 'Error activating IFactory
More than one matching bindings are available.
Matching bindings:
  1) binding from IFactory to IocFactory
  2) binding from IFactory to NinjectFactory
Activation path:
  2) Injection of dependency IFactory into parameter factory of constructor of type StandardRuleParser
  1) Request for StandardRuleParser

Suggestions:
  1) Ensure that you have defined a binding for IFactory only once.
```

This is due to [this line](https://github.com/Bikeman868/UrlRewrite.Net/blob/master/Solution/UrlRewrite-Net40/Package.cs#L68) in the `Package` class.

My workaround is `kernel.Unbind<IFactory>();` before loading my own `IFactory` implementation into Ninject

**Comment by Bikeman868** [comment]
Can you share your code please.

The Ioc.Modules library is designed to handle the case where there are multiple packages that register the same interface and I have lots of occurrences of this in my own code. In these cases Ioc.Modules will try to identify which assembly is the entry point for your application and will give priority to the registrations made there. You can also explicitly add assemblies to the `PackageLocator` instance to define the order of precedence.

Ninject also has a `Rebind<T>()` method that does not error if the binding already exists.

If I can see your code then I should be able to help you to get to the best solution.

**Comment by Bikeman868** [comment]
Since you did not respond for two weeks I am closing this issue. If you are still experiencing problems feel free to reopen it. Thanks.
