### ISSUE TITLE
1.2.8 has other protection levels

### ISSUE THREAD

**Issue by BvdVen** [Bikeman868/UrlRewrite.Net#16]
I've updated UrlRewrite.Net to 1.2.8 today and also the related packages. But now I get exceptions that multiple classes are inaccessible due to its protection level.

- AbsoluteUrlOperation
- LowerCaseOperation
- UpperCaseOperation
- UrlEncodeOperation
- UrlDecodeOperation
- UrlRewriteException

**Comment by Bikeman868** [comment]
Having these classes public makes it very difficult to release new versions without breaking other people's code, and this could cripple any further development effort.

I don't think your application should be referring to the concrete implementations of these interfaces. The solution uses IoC, enabling you to obtain a concrete implementation via the interface, which would seem to be a much better way of working.

**Comment by BvdVen** [comment]
Ok, I should use the interfaces indeed.
