### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stherrienaspnet** [Bikeman868/UrlRewrite.Net#18]
Hello could you tell me if your module could help me with my specific use case.

Let say my web application will be hosted on port 80. I need to  reverse proxy request containing /api/
as example http://localhost/api/sessions/signin need to be redirect as  http://localhost:5000/api/sessions/signin

Thanks in advance for your help

**Comment by Bikeman868** [comment]
It does not support reverse proxy. For me this is a completely different use case than url rewriting and I am a strong believer in single responsibility

**Comment by stherrienaspnet** [comment]
Thanks

Le jeu. 31 mai 2018 10:05 PM, Martin Halliday <notifications@github.com> a
écrit :

**Comment by Bikeman868** [comment]
For anyone following this thread you might be interested to know that I have built an open-source load-balancer called "Gravity". One of the available processing nodes that can be configured implements these rewriting rules - I copied the code directly over so it's fully compatible.
Check out my "Gravity" repo.
