### ISSUE TITLE
Image rewrite best practice

### ISSUE THREAD

**Issue by wesquare** [Bikeman868/UrlRewrite.Net#19]
Hi!
We want to rewrite all image url's from:
https://url/productimage/shoppingcart/test.jpg
into
https://url/product_images/test.jpg?preset=shoppingcart

We came up with the following rule, which seems to work:
```
<rule name="ProductImages"  stopProcessing="true">
      <conditions>
        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
        <condition scope="pathElement" index="1" test="equals" value="productimage"  />
        <condition scope="pathElement" index="2" test="equals" value="" negate="true" />
        <condition scope="pathElement" index="3" test="equals" value="" negate="true" />
      </conditions>
      <action type="Rewrite" url="/product_images/" />      
      <append scope="path" from="originalPathElement" fromIndex="3" />
      <append scope="url" value="?preset=" />
      <append scope="url" toIndex="preset" from="originalPathElement" fromIndex="2" />
    </rule>
```

Is this the best/fastest way to do it? Or should we add a match url part and maybe remove some conditions to make it faster?

Thanks,
Walter

**Comment by Bikeman868** [comment]
Hi Walter,

Sorry, I missed the email notification and did not know about this issue until I noticed it just now.

The rather late answer to your question is that this fairly long winded way of writing the rules is by far the fastest in terms of execution time. The various conditions and actions get compiled down into Lambda expressions that then get converted into machine code, so this rule should only add a few microseconds to the request processing time.

Thank you for using my open source software :-)

**Comment by Bikeman868** [comment]
One thing to note is that checking for the existence of a file or directory takes much longer than comparing strings, so you should do the path comparison first and the file and directory existence checks after.
