### ISSUE TITLE
Online rewrite rules tester

### ISSUE THREAD

**Issue by ericnewton76** [Bikeman868/UrlRewrite.Net#22]
Hey I was debating standing up an online rewrite rules tester using this module.  Was wondering if you're cool with that and any pitfalls you might see?

Reason I was going to do an online version is because I dont even have IIS installed on latest Dev machine, but needed to test some new rewrite rules.

I would have two "modes": standard IIS rewrite and yours that adds all the additional stuff. (But using yours to validate both since the IIS rewrite module isnt a net dll)

**Comment by Bikeman868** [comment]
I think that would be a great addition. Bear in mind that many users have custom classes that are referenced by their rules.

**Comment by ericnewton76** [comment]
Hmmm, we might not be able to support the custom classes but will be able to provide testing and validation of their non-custom class based rules.

Eventually, if they keep their custom classes in a specific file, we could eventually allow that file to get compiled or possibly run their uploaded dll in a separate appdomain.  Man that would be a cool feature, lol

**Comment by Bikeman868** [comment]
I have projects where custom logic has the data access and caching layers dependency injected. This is a common use case that I have heard from other users of the package too.

Maybe compiling into a separate dll would work for some people.

**Comment by Bikeman868** [comment]
I should point out that this package already contains a request tracing feature to help with debugging your rules. The trace produces a detailed output of rules, results of conditions tested, modifications made to the request etc.

**Comment by Bikeman868** [comment]
It's been a month, do you still want to keep this ticket open?
