### ISSUE TITLE
UrlRewrite looking for files at an incorrect path

### ISSUE THREAD

**Issue by Gantonator** [Bikeman868/UrlRewrite.Net#23]
If the web application is hosted on a network share (visible to the IIS webserver), then it looks as if initialising UrlRewrite in the Global.asax causes an error when the .Initialize method attempts to find the RewriteRules.config(?).

You can see here that a DirectoryNotFoundException is generated when looking for "c:\temp\another\bin" (on the webserver), when the web application is actually located at ""\\share\temp\another\bin".

`[DirectoryNotFoundException: Could not find a part of the path 'c:\temp\another\bin'.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +271
   System.IO.FileSystemEnumerableIterator`1.CommonInit() +411
   System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) +488
   System.IO.Directory.GetFiles(String path, String searchPattern) +106
   Ioc.Modules.PackageLocator.ProbeBinFolderAssemblies(IPropertyBag properties) +133
   UrlRewrite.Utilities.NinjectFactory..ctor() +47
   UrlRewrite.RewriteModule.Initialize(ILog log, Func`2 forwardTracePredicate, Func`2 reverseTracePredicate, IFactory factory, Stream ruleStream, IRuleParser ruleParser) +74
   DA.OEMS.MvcApplication.Application_Start() +127

[HttpException (0x80004005): Could not find a part of the path 'c:\temp\another\bin'.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +520
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +176
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +165
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +267
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +341

[HttpException (0x80004005): Could not find a part of the path 'c:\temp\another\bin'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +523
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +107
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +688`

**Comment by Bikeman868** [comment]
I didn’t test this configuration. I will take a look at the code and see if there is a way to write it that works for both cases

**Comment by Bikeman868** [comment]
The Initialize method can be passed a `Stream` to load the rewrite rules from. This allows you to open the rules file in whatever way works fro your application.

If you do not pass a `Stream` then the following code applies.

```
if (ruleStream == null)
{
   var filePath = HttpContext.Current.Server.MapPath("~/RewriteRules.config");
   ruleStream = File.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.Read);
}
```

In this case the behavior is defined by ASP.Net. I did some research on ways to determine the application home path and in the .Net framework there is no method that works reliably for all types of application.

**Comment by Gantonator** [comment]
Hi, sorry for the delay on this.  The RewriteRules.config is actually a red herring.  Even when loading the RewriteRules as a stream (and deleting RewriteRules.config completely), the problem persisted.

What's actually happening is that the application is looking for a directory in the incorrect place.  Here's what's I found:

Hosting on IIS, I have the site physical path set to **\\somesharelocation\temp\another**.  Attempting to visit the site gives:

```
Could not find a part of the path 'c:\temp\another\bin'. 
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
Stack Trace: 
[DirectoryNotFoundException: Could not find a part of the path 'c:\temp\another\bin'.]    System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +271
    System.IO.FileSystemEnumerableIterator`1.CommonInit() +411
    System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) +488
System.IO.Directory.GetFiles(String path, String searchPattern) +106
Ioc.Modules.PackageLocator.ProbeBinFolderAssemblies(IPropertyBag properties) +133
UrlRewrite.Utilities.NinjectFactory..ctor() +47
UrlRewrite.RewriteModule.Initialize(ILog log, Func`2 forwardTracePredicate, Func`2 reverseTracePredicate, IFactory factory, Stream ruleStream, IRuleParser ruleParser) +74    
DA.OEMS.MvcApplication.Application_Start() +127  [HttpException (0x80004005): Could not find a part of the path 'c:\temp\another\bin'.]    System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +520    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +176    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +165    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +267    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +341  [HttpException (0x80004005): Could not find a part of the path 'c:\temp\another\bin'.]    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +523    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +107    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +688
--
```
If I then do create the **empty** directory on the webserver at **C:\temp\another\bin**, the site loads correctly.

**Comment by Gantonator** [comment]
I noticed in issue #2 that changing from ```PackageLocator().ProbeBinFolderAssemblies()``` to ```PackageLocator().ProbeAllLoadedAssemblies();``` solved a dependency problem, using your Readme I constructed this factory
```
public class FactoryForUrlRewrite : IFactory
{
    private readonly IKernel _ninject;

    public FactoryForUrlRewrite()
    {
        var packageLocator = new PackageLocator().ProbeAllLoadedAssemblies();
        _ninject = new StandardKernel(new Ioc.Modules.Ninject.Module(packageLocator));
        _ninject.Rebind<IFactory>().ToConstant(this);
    }

    T IFactory.Create<T>()
    {
        return _ninject.Get<T>();
    }

    object IFactory.Create(Type type)
    {
        return _ninject.Get(type);
    }
}
```
and passed it here
```
            UrlRewrite.RewriteModule.Initialize(factory: new FactoryForUrlRewrite());
```

Which seemed to resolve the issue.
