### ISSUE TITLE
Condition help?

### ISSUE THREAD

**Issue by grahambunce** [Bikeman868/UrlRewrite.Net#24]
Hi,

I'm trying to use this package due to it's custom re-writer capabilities; effectively as a reverse proxy. What I'm trying to do is to intercept every call, inspect the POST data based on this data, and then make a decision to redirect to server A or server B.

I think I need a custom condition, but I can't work out how to invoke this - I've created a test project and I can't work out how to invoke my condition; it never appears to be called.

Can you provide some advice please?

**Comment by Bikeman868** [comment]
Url rewriting and reverse proxy are quite different things. I know that Microsoft combined them in their rewrite but I don’t think they belong together.

I have another open source project called Gravity that is a load balancer. It contains the rules engine from url rewriter and also does reverse proxy and many other filtering and routing functions.

**Comment by Bikeman868** [comment]
The Gravity load-balancer is undergoing final production load testing.
I would be interested to hear any feedback you might have about it.
