### ISSUE TITLE
Recommendation for improved Trace logging and Debugging

### ISSUE THREAD

**Issue by cajuncoding** [Bikeman868/UrlRewrite.Net#3]
This is a great solution project and has been very valuable on my projects!  Thanks for all the hard work!

I have recommendation that occurred to me when I first looked at your trace outputs.  It would be extremely useful if the trace lines also output the dynamic values that it compares against (e.g. the expanded value of {} macro expressions or the actual value of Header/ServerVariable).

For example, in the Trace line below:
`Rewrite:    8.6mS         request ServerVariable[SERVER_PORT] MatchRegex '53105' is false`

It would be significantly more useful if it said something more like:
`Rewrite:    8.6mS         request ServerVariable[SERVER_PORT]='8080' MatchRegex '53105' is false`

Another example might be:
`Rewrite:    9.5mS         request Header[HOST] MatchRegex 'localhost' is true`

would be much easier to debug if it said:
`Rewrite:    9.5mS         request Header[HOST]='localhost' MatchRegex 'localhost' is true`

Would appreciate your thoughts on this as an improvement for any dynamic value or macro expansion, etc. ?

**Comment by Bikeman868** [comment]
I think this is a great idea, I will add it to my to-do list.

**Comment by Bikeman868** [comment]
Hi raerae1616 please try this version `Install-Package UrlRewrite.Net -Version 1.2.2` 
Let me know if it works for you, then I will make it the published version.
Thanks,

**Comment by Bikeman868** [comment]
These changes are now in the published version

**Comment by cajuncoding** [comment]
The updated debug outputs ate great and significantly more useable now for quick glance debugging! Thanks! 

Now I'm really looking forward to UrlRewrite.Net support (and improvements/optimizations) for Outbound post-processing rules... Which t my current project also uses.
