### ISSUE TITLE
Initialize Exception

### ISSUE THREAD

**Issue by BvdVen** [Bikeman868/UrlRewrite.Net#5]
I followed the steps to get started but I get the exception below when the "Initialize()" method is called:

```
protected void Application_Start(object sender, EventArgs e)
        {
            UrlRewrite.RewriteModule.Initialize();
}
```

> Exception information: 
>     Exception type: HttpException 
>     Exception message: Method not found: 'System.Collections.Generic.IList`1<Ioc.Modules.IocRegistration> Ioc.Modules.PackageLocator.GetAllRegistrations()'.
>    at System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app)
>    at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
>    at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
>    at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
>    at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
> 
> Method not found: 'System.Collections.Generic.IList`1<Ioc.Modules.IocRegistration> Ioc.Modules.PackageLocator.GetAllRegistrations()'.
>    at Ioc.Modules.Ninject.Module.Load()
>    at Ninject.KernelBase.Load(IEnumerable`1 m)
>    at UrlRewrite.Utilities.NinjectFactory..ctor()
>    at UrlRewrite.RewriteModule.Initialize(ILog log, Func`2 forwardTracePredicate, Func`2 reverseTracePredicate, IFactory factory, Stream ruleStream, IRuleParser ruleParser)
>    at Prijsvrij.Website.Global.Application_Start(Object sender, EventArgs e) in c:\ForrestApplications\Prijsvrij-2013\Website\App_Code\Global.asax.cs:line 32

**Comment by Bikeman868** [comment]
Method not found errors are usually caused by running against a different version of an assembly than the version that was used at compile time. The missing method in this case is from the Ioc.Modules assembly. Can you either update to the latest versions of all NuGet packages or match your versions to the ones that UrlRewrite was build with.

Assuming you have UrlRewrite version 1.2.1 (the latest stable version) it was build against Ioc.Modules version 1.1.2 (the latest stable version is 1.1.3).

**Comment by BvdVen** [comment]
Ok, I just got the UrlRewriter package from the nugetpackage manager and automatic the other packages are installed. I could expect the latest versions are downloaden. I'm not able too look into it right now but will keep you updated!

**Comment by BvdVen** [comment]
I updated all packages and it seems to work now!

```
<package id="Ioc.Modules" version="1.1.3" targetFramework="net45" />
<package id="Ioc.Modules.Ninject" version="1.1.3" targetFramework="net45" />
<package id="Ninject" version="3.2.2.0" targetFramework="net45" />
<package id="UrlRewrite.Net" version="1.2.1" targetFramework="net45" />
```
