### ISSUE TITLE
CombineConditions() throws Exception

### ISSUE THREAD

**Issue by BvdVen** [Bikeman868/UrlRewrite.Net#6]
I don't know if this is something you want to prevent in ConditionList.cs or should be done in the parser. Currently when I use the CombineConditions like in your StandardParser and c2.conditions is null an exception is thrown up.

```
public IConditionList Add(ICondition condition)
        {
            if (_conditions == null) _conditions = new List<ICondition>();

            var conditionList = condition as ConditionList;
            if (conditionList == null 
                || conditionList._logic != _logic 
                || conditionList._trackAllCaptures != _trackAllCaptures)
                _conditions.Add(condition);
            else
                _conditions.AddRange(conditionList._conditions); //Not possible when conditionList._conditions == null

            return this;
        }
```

**Comment by Bikeman868** [comment]
I guess the original code never combines an empty condition list with another condition list. This kind of makes sense since there isn't much point in constructing a condition list with no conditions in it.
If this is causing a problem for you I can easily add a null reference check.

**Comment by Bikeman868** [comment]
I added the null reference check as described above.
