### ISSUE TITLE
Cannot move rewrite section to separate .config

### ISSUE THREAD

**Issue by Koryakov** [Bikeman868/UrlRewrite.Net#8]
Hi!
I cannot move rewrite section to separate .config:
![image](https://cloud.githubusercontent.com/assets/13645671/21743081/07b05bdc-d50c-11e6-9694-16133739a9f3.png)
Error: configSource attribute is not declared
![image](https://cloud.githubusercontent.com/assets/13645671/21743098/5631e3ac-d50c-11e6-9625-76663db654d7.png)

Environment:
VS 2015 Update 3
MVC 5
IIS 10
.Net Framework 4.6.1

Thank you!

**Comment by Bikeman868** [comment]
Hi,

You do not need to have anything in your web.config for the rewriter to work. This optional step will allow you to switch back to the Microsoft one later if you want to.

For the rewriter to work you just need to put your rules in a file in the root folder of your web site.

Martin

**Comment by Bikeman868** [comment]
I forgot to mention that if you want to add this section to your config, it can not be inside another section.
