### ISSUE TITLE
rewriteMap case insensitive

### ISSUE THREAD

**Issue by Koryakov** [Bikeman868/UrlRewrite.Net#9]
Hi! Some questions
1)  Is it possible to use case insensitive keys in rewriteMap?
For example:
"/my-test-page" and "/My-Test-page" both redirect to single Pascal-casing page "/My-test-page"

2) 
"/Category/Article-{many different page endings}" and "/Category/article-{many different page endings}" both redirect to "/Category/Page-{many different page endings}"
( So to change "Article-*" and "article-*" to "Page-*" )

Thank you.

**Comment by Bikeman868** [comment]
Hi,

1. Rewrite maps are already case insensitive, in fact there is no option to make them case sensitive.

2. There are several ways of doing this, including a regex match with match group replace. You also have the option to write an operation in C# to do whatever you want.

You might also want to consider putting a rule at the top of your rules file that changes the whole path to lower case before doing anything else. This might simplify your code as well as the rewrite rules. A rule like this would look like this:

```
<rule name="Make path lower case">
  <rewrite to="Path" from="Path" operation="ToLower" />
</rule>
```
